---
title: "Welcome to Data Analysis!"
format:
  html:
    link-external-icon: true
    link-external-newwindow: true
---

Welcome to the course website for ST201 Data Analysis!

[Module information](https://ncahill89.github.io/ST201/0-Information.html)

Lecture material (slides, notes, videos) are licensed under CC-BY-NC 4.0.

Contact: Niamh Cahill (niamh.cahill\@mu.ie)

## Lecture Slides

### Week 1

1a. [Data](https://ncahill89.github.io/ST201/1-Data.html)

1b. Code lecture; check the [Rstudio Sever](https://rstudio.maths.nuim.ie) for Week1_Data.R

### Week 2

2a. [Numerical Data](https://ncahill89.github.io/ST201/2-Numerical.html)

2b. Code lecture; check the [Rstudio Sever](https://rstudio.maths.nuim.ie) for Week2_NumericalData.R

### Week 3

3a. [Association between Categorical Variables](https://ncahill89.github.io/ST201/3-Categorical.html)

3b. Code lecture; check the [Rstudio Sever](https://rstudio.maths.nuim.ie) for Week3_Categorical.R

### Week 4

4a. [Association between Categorical Variables (2)](https://ncahill89.github.io/ST201/4-Categorical2.html)

4b. Code lecture; check the [Rstudio Sever](https://rstudio.maths.nuim.ie) for Week4_Categorical(2).R

### Week 5

5a. [Association between Categorical Variables (3)](https://ncahill89.github.io/ST201/5-Categorical3.html)

5b. Code lecture; check the [Rstudio Sever](https://rstudio.maths.nuim.ie) for Week5_Categorical(3).R

### Week 6

6a. [Discrete Probability Distributions](https://ncahill89.github.io/ST201/6-DiscretePDFs.html)

6b. Code lecture; check the [Rstudio Sever](https://rstudio.maths.nuim.ie) for Week6_Discrete.R

### Week 7

Midterm exam week

### Week 8

8a. [Continuous Probability Distributions](https://ncahill89.github.io/ST201/8-ContinuousPDFs.html)

8b. Code lecture; check the [Rstudio Sever](https://rstudio.maths.nuim.ie) for Week8_Continuous.R


### Week 9

9a. [Single Samples](https://ncahill89.github.io/ST201/9-SingleSamples.html)

9b. Code lecture; check the [Rstudio Sever](https://rstudio.maths.nuim.ie) for Week9_SingleSamples.R


### Week 10

10a. [Inference for Means](https://ncahill89.github.io/ST201/10-tests.html)

10b. Code lecture; check the [Rstudio Sever](https://rstudio.maths.nuim.ie) for Week10_InferenceMeans.R


### Week 11
11a. [Simple Linear Regression]()

11b. Code lecture; check the [Rstudio Sever](https://rstudio.maths.nuim.ie) for Week11_SLR.R


## Tutorial Sheets

[Tutorial Sheet 1: Numerical Data](https://ncahill89.github.io/ST201/Tutorial1.html)

[Tutorial Sheet 2: Categorical Data](https://ncahill89.github.io/ST201/Tutorial2.html)

[Tutorial Sheet 3: Discrete Distributions](https://ncahill89.github.io/ST201/Tutorial3.html)

[Tutorial Sheet 4: Continous Distributions, CLT and Confidence Intervals](https://ncahill89.github.io/ST201/Tutorial4.html)

